### PR TITLE
Add font awesome support to smart icons

### PR DESCRIPTION
**Pull request by lawgsy**

### CODE REVIEW

**Comment by lawgsy** [comment]
~Something appears to be wrong. I'm looking into the issue right now.~
I believe all is well.

**Comment by lawgsy** [comment]
I believe all is well.

**Review by KELiON — APPROVED** [review]

**Comment by KELiON** [comment]
Nice improvement!

**Comment by KELiON** [comment]
I already merged your PR when noticed, that you didn't add `react-fontawesome` to dependencies, can you do it please?

**Pull request merged**
